### PR TITLE
fix Linux build

### LINKED ISSUE #67: Trying to compile it for linux
Hello. 

I'm following the instructions to compile on linux64, i tried with OF .9.6 and .9.8 but this issue appears: 

```
  make
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 rtaudio gl glu glew gtk+-3.0 libmpg123 
Compiling OF library for Release
make[1]: Entering directory '/home/inferi/ExternalSoftware/of_v0.9.8_linux64_release/libs/openFrameworksCompiled/project'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 rtaudio gl glu glew gtk+-3.0 libmpg123 
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 rtaudio gl glu glew gtk+-3.0 libmpg123 
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 rtaudio gl glu glew gtk+-3.0 libmpg123 
Done!
make[1]: Leaving directory '/home/inferi/ExternalSoftware/of_v0.9.8_linux64_release/libs/openFrameworksCompiled/project'


Compiling Oscilloscope for Release
make[1]: Entering directory '/home/inferi/ExternalSoftware/os2/Oscilloscope'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 rtaudio gl glu glew gtk+-3.0 libmpg123 
make[1]: execvp: /bin/sh: Argument list too long
make[1]: *** [/home/inferi/ExternalSoftware/of_v0.9.8_linux64_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:190: obj/linux64/Release/.compiler_flags] Error 127
make[1]: Leaving directory '/home/inferi/ExternalSoftware/os2/Oscilloscope'
make: *** [/home/inferi/ExternalSoftware/of_v0.9.8_linux64_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:130: Release] Error 2
```

### PR DESCRIPTION
**Pull request by s-ol**
close #67

### CODE REVIEW

**Comment by s-ol** [comment]
submodule merge checklist:

- [x] ofxSyphon
- [ ] ofxSpout (waiting for upstream)
- [x] ofxFontStash2
- [x] ofxNative
- [ ] ofxAvCodec (waiting for @kritzikratzi)

**Comment by s-ol** [comment]
ping :slightly_smiling_face:

**Comment by kritzikratzi** [comment]
pong! 

just busy with other stuff. tomorrow/thursday!

**Comment by kritzikratzi** [comment]
hi! 

short update: finally had some time try this out. 
i had to make a small adjustment for ofxLibsamplerate, other than that it just worked, hurray ^^ 

thx for your hard work, gonna merge this soon!

**Comment by kritzikratzi** [comment]
hi! 

thanks a lot, i have finally (FINALLY!) taken the time to implement this. i didn't merge it because of the submodule mess, but this wouldn't have been possible without your contribution.

**Pull request closed without merging**
